[project]
name = "research_server"
version = "0.1.0"
description = "Basic Model Context Protocol (MCP) server for research paper search."
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.51.0",
    "arxiv>=2.2.0",
    "mcp>=1.8.1",
    "nest-asyncio>=1.6.0",
]
